In [45]:
import pandas as pd
import numpy as np
import random

In [119]:
df = pd.read_csv(r'C:\Users\1507828\Desktop\New shift.csv')

In [120]:
df.head()

,DAYS,DATES,NISHITA,BHUSHAN,SWAPNIL,AVINASH,PUSHPA,LALITH,ANCHIT,SANJEEV,HARISH,SAITEJA,MARIO,ALEXIS,PUNDALEEK,CHRISMA
0,Friday,7-3-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Saturday,7-4-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sunday,7-5-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Monday,7-6-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tuesday,7-7-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
dfno=df.iloc[:,2:]

In [110]:
dff=df[df['DAYS'] == 'Saturday']

In [89]:
df.columns

Index(['DAYS', 'DATES', 'NISHITA', 'BHUSHAN', 'SWAPNIL', 'AVINASH', 'PUSHPA',
       'LALITH', 'ANCHIT', 'SANJEEV', 'HARISH', 'SAITEJA', 'MARIO', 'ALEXIS',
       'PUNDALEEK', 'CHRISMA'],
      dtype='object')

In [87]:
df[df['DAYS'] == 'Sunday'].T

                 2          9          16         23        30
DAYS         Sunday     Sunday     Sunday     Sunday    Sunday
DATES      7-5-2020  7-12-2020  7-19-2020  7-26-2020  8-2-2020
NISHITA         NaN        NaN        NaN        NaN       NaN
BHUSHAN         NaN        NaN        NaN        NaN       NaN
SWAPNIL         NaN        NaN        NaN        NaN       NaN
AVINASH         NaN        NaN        NaN        NaN       NaN
PUSHPA          NaN        NaN        NaN        NaN       NaN
LALITH          NaN        NaN        NaN        NaN       NaN
ANCHIT          NaN        NaN        NaN        NaN       NaN
SANJEEV         NaN        NaN        NaN        NaN       NaN
HARISH          NaN        NaN        NaN        NaN       NaN
SAITEJA         NaN        NaN        NaN        NaN       NaN
MARIO           NaN        NaN        NaN        NaN       NaN
ALEXIS          NaN        NaN        NaN        NaN       NaN
PUNDALEEK       NaN        NaN        NaN        NaN       NaN
CHRISMA         NaN        NaN        NaN        NaN       NaN

In [121]:
df= df.set_index(['DAYS','DATES'])

In [55]:
df.head()

,,NISHITA,BHUSHAN,SWAPNIL,AVINASH,PUSHPA,LALITH,ANCHIT,SANJEEV,HARISH,SAITEJA,MARIO,ALEXIS,PUNDALEEK,CHRISMA
DAYS,DATES,,,,,,,,,,,,,,
Friday,7-3-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Saturday,7-4-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sunday,7-5-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monday,7-6-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tuesday,7-7-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df.columns

Index(['NISHITA', 'BHUSHAN', 'SWAPNIL', 'AVINASH', 'PUSHPA', 'LALITH',
       'ANCHIT', 'SANJEEV', 'HARISH', 'SAITEJA', 'MARIO', 'ALEXIS',
       'PUNDALEEK', 'CHRISMA'],
      dtype='object')

In [122]:
for i in df.columns:
    df[i] = df[i].apply(lambda v: np.random.choice([1,2]))

In [123]:
df

,,NISHITA,BHUSHAN,SWAPNIL,AVINASH,PUSHPA,LALITH,ANCHIT,SANJEEV,HARISH,SAITEJA,MARIO,ALEXIS,PUNDALEEK,CHRISMA
DAYS,DATES,,,,,,,,,,,,,,
Friday,7-3-2020,2,1,2,1,1,2,1,1,2,2,2,1,1,2
Saturday,7-4-2020,1,2,2,2,2,1,2,1,1,2,2,1,2,1
Sunday,7-5-2020,1,1,1,2,1,2,1,1,1,2,1,2,1,1
Monday,7-6-2020,1,1,1,2,2,1,1,2,1,1,1,1,2,1
Tuesday,7-7-2020,1,2,1,2,2,2,1,2,1,1,1,2,1,2
Wednesday,7-8-2020,1,1,2,1,2,1,2,2,1,2,2,1,2,2
Thursday,7-9-2020,1,2,2,1,2,2,2,1,1,1,1,2,2,1
Friday,7-10-2020,2,2,1,1,2,2,1,1,2,2,2,2,1,1
Saturday,7-11-2020,2,1,1,1,2,1,1,2,1,1,2,1,2,2
Sunday,7-12-2020,1,1,1,1,1,1,1,2,2,2,2,1,1,2
Monday,7-13-2020,1,1,1,2,2,2,1,2,2,2,1,1,2,2
Tuesday,7-14-2020,2,2,1,2,2,1,2,2,2,2,2,2,2,2
Wednesday,7-15-2020,2,2,2,2,2,2,2,1,2,1,2,1,2,2
Thursday,7-16-2020,2,1,1,2,1,1,2,2,2,2,2,2,1,2
Friday,7-17-2020,1,1,2,2,1,1,2,1,2,1,2,1,2,1
Saturday,7-18-2020,1,2,1,2,2,1,2,1,2,1,2,2,2,1
Sunday,7-19-2020,2,2,2,1,2,1,1,1,1,1,1,1,2,2
Monday,7-20-2020,2,2,2,2,2,1,1,1,2,2,1,1,1,2
Tuesday,7-21-2020,1,2,2,2,1,2,1,2,1,1,2,1,2,2
Wednesday,7-22-2020,1,2,2,1,2,1,1,1,2,1,2,2,2,2
Thursday,7-23-2020,2,1,2,1,1,2,1,2,2,1,2,2,2,2
Friday,7-24-2020,2,1,1,1,2,2,2,2,1,1,1,2,2,1
Saturday,7-25-2020,2,1,2,2,1,1,2,1,1,1,2,2,1,1
Sunday,7-26-2020,2,2,1,2,2,1,1,1,2,1,2,2,2,1
Monday,7-27-2020,2,1,1,1,1,2,2,1,2,1,2,2,1,1
Tuesday,7-28-2020,1,1,1,1,2,2,1,1,2,2,1,1,2,2
Wednesday,7-29-2020,1,1,2,1,2,2,2,1,1,1,2,1,2,2
Thursday,7-30-2020,2,2,1,1,2,2,1,2,1,1,2,2,1,2
Friday,7-31-2020,2,2,1,2,1,1,1,2,1,2,1,2,2,1
Saturday,8-1-2020,2,2,2,1,1,1,2,2,2,2,1,1,1,2
Sunday,8-2-2020,1,1,2,1,2,1,1,1,1,1,1,1,2,1